### PR TITLE
make it better

### PR DESCRIPTION
**Pull request by retron-but-2**

### CODE REVIEW

**Comment by retron-but-2** [comment]
:shipit:

**Comment by Explosion-Scratch** [comment]
uhmmm

**Comment by retron-but-2** [comment]
do it

**Comment by Explosion-Scratch** [comment]
if you add something ill merge (only if it actually doesn't wreck the whole idea)

**Comment by retron-but-2** [comment]
hmm

**Comment by retron-but-2** [comment]
ok give me some time to think

**Comment by Explosion-Scratch** [comment]
You could try adding randomness to the reponame, like `[username]-is-epic` or `[username]-is-awesome`

**Comment by Explosion-Scratch** [comment]
ok

**Comment by retron-but-2** [comment]
> You could try adding randomness to the reponame, like `[username]-is-epic` or `[username]-is-awesome`

how do i do that 😆

**Comment by retron-but-2** [comment]
idrk know how to code in github actions

**Comment by Explosion-Scratch** [comment]
i can halp in disc dms

**Pull request closed without merging**
